// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwEfPZUYkUa4w065328dXePOm_tVYcGPw',
    appId: '1:861038582754:web:a002ffe0c3932aadd0b7bb',
    messagingSenderId: '861038582754',
    projectId: 'coinwave-backend',
    authDomain: 'coinwave-backend.firebaseapp.com',
    storageBucket: 'coinwave-backend.appspot.com',
    measurementId: 'G-SG5QNVHBG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT2Hjm81h3DW4g1uXUvrqz4dYmBW9djZ4',
    appId: '1:861038582754:android:f18411d4d18fd25fd0b7bb',
    messagingSenderId: '861038582754',
    projectId: 'coinwave-backend',
    storageBucket: 'coinwave-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt1vJbHti-S-6I2vIe89xJivUDv1XrUWE',
    appId: '1:861038582754:ios:88e2f8cef11490a7d0b7bb',
    messagingSenderId: '861038582754',
    projectId: 'coinwave-backend',
    storageBucket: 'coinwave-backend.appspot.com',
    iosBundleId: 'com.example.coinwave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt1vJbHti-S-6I2vIe89xJivUDv1XrUWE',
    appId: '1:861038582754:ios:88e2f8cef11490a7d0b7bb',
    messagingSenderId: '861038582754',
    projectId: 'coinwave-backend',
    storageBucket: 'coinwave-backend.appspot.com',
    iosBundleId: 'com.example.coinwave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwEfPZUYkUa4w065328dXePOm_tVYcGPw',
    appId: '1:861038582754:web:a83356a9bd869681d0b7bb',
    messagingSenderId: '861038582754',
    projectId: 'coinwave-backend',
    authDomain: 'coinwave-backend.firebaseapp.com',
    storageBucket: 'coinwave-backend.appspot.com',
    measurementId: 'G-KT84ZPY8HP',
  );
}
